### ISSUE TITLE
get ASDs.json (if missing) on any asset pull

### ISSUE THREAD

**Issue by stolarczyk** [refgenie/refgenconf#117]
in case of `refgenie pull <genome>/<fasta_child>`, only the genome digest is fixed (the ASDs file is missing)
so this genome can't be compared if the fasta was not built or pulled prior to this
the fasta asset specifically has to be pulled or built to get the ASDs

I suppose it wouldn't be hard to make pull include the ASD since it lives at the genome level and not in the fasta asset.

**Comment by stolarczyk** [comment]
The reason why ASDs.json files are only created when fasta asset is present because they are simply not served by refgenieserver. We don't have a concept of serving files that are not assets.

This shortcoming could be resolved by getting these genome metadata from a seqcol server, which doesn't exist yet.

**Comment by nsheff** [comment]
@stolarczyk is this resolved now that the server does server those ASDs with an endpoint?

**Comment by stolarczyk** [comment]
> now that the server does server those ASDs with an endpoint?

are you referring to seqcol server? refgenieserver does not serve them as far as I remember

Either way, I don't think it's solved yet
